### ISSUE TITLE
histdb --in overwrites the current directory in the prompt with `~dir`

### ISSUE THREAD

**Issue by a3ammar** [larkery/zsh-histdb#1]
Hi,
Awesome utility, really love it. One small issue: the current directory in my prompt gets overwritten with `~dir` if I use `histdb --in` without any arguments.

I use [prezto](https://github.com/sorin-ionescu/prezto) and here's my current prompt: `%F{223}%m%f %F{69}${%2~}%(!. %B%F{1}#%f%b.)`.

Do you have any suggestions?

**Comment by larkery** [comment]
That's weird; my best guess here is that I have been lazy and not specified a variable as local, and that running with --in is setting a variable which is included in your prompt somehow. On the other hand, you are using prompt variables like `%~` rather than $SOMETHING.

I will review the code and make sure everything is local, and maybe that will help...

**Comment by larkery** [comment]
I've pushed some changes which I think make all the variables local, which may fix the issue.

**Comment by a3ammar** [comment]
Thank you, that fixes it!

The `%2~` is a quick way to have only current directory and its parent in the prompt, do you have a better replacement? Googling around I found `$(basename $(dirname "$PWD"))/$(basename "$PWD")` but that is kind of ugly.

**Comment by larkery** [comment]
I think that `%2~` is the Right Way To Do It, and the problem must have been my code side-effectishly setting some shell variable.

What suprises me is that when the prompt expands `%2~` it isn't just looking at some ZSH internal knowledge of the current working directory, and instead is something that can be broken like this.

Plus I have a `%~` in my prompt string which works OK. All very mysterious, but I'm happy it's fixed.
