### ISSUE TITLE
column: read failed: Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by diamond-lizard** [larkery/zsh-histdb#12]
When I run `"histdb --limit 19577"` I get an error saying `"column: read failed: Invalid or incomplete multibyte or wide character"`

I have nearly 20000 entries in my history, and as my history grows, the number I can pass to histdb's --limit argument without issues also increases.  For instance, some entries back I was limited to only `"histdb --limit 19564"` but after running some other commands, now histdb displays history fine up to `"histdb --limit 19576"`.  Also, passing any number greater than 19577 also results in the same error.

To me this looks like this error is triggered when I specify a limit that exceeds (or maybe reaches) the number of entries in the histdb database.  But I have no way of knowing if that's the case because I don't know how many entries are actually in my the database.

When I pass the -d flag to histdb (as `"histdb -d --limit 19577"`) the result is:

```
select strftime(case when datetime(max_start, 'unixepoch') > datetime('now', 'start of day') then '%H:%M' else '%d/%m' end, max_start, 'unixepoch') as time, session as ses, dir, argv as cmd from (select session, replace(places.dir, '/home/me', '~') as dir, replace(commands.argv, '
', '
^_^_^_') as argv, max(start_time) as max_start
from
  history
  left join commands on history.command_id = commands.rowid
  left join places on history.place_id = places.rowid
where not (commands.argv like 'histdb%') and places.host='myhost'
group by history.command_id, history.place_id
order by max_start desc
limit 19577) order by max_start asc
```

**Comment by larkery** [comment]
I think you probably have an entry typed into the history that includes an invalid unicode character, or something about your locale is upsetting it. I use a funny UTF-8 character (field separator I think?) to do the columns in the output, which _could_ be a problem, but it would seem odd if it works most of the time but not all the time.

So, diagnostically:

1. Do you have a unicode-safe locale configured (I have only tested with UTF-8 EN GB)
2. If you modify the histdb query function to disable piping to `column`; modify line 280 to read something like:
```
        _histdb_query -header -separator ", " "$query"
```
and see if that works. If it does, then it is some bad character upsetting `column`; you can use `hexdump` or similar to see what raw character codes are coming out, and bisect on the value of `--limit` to see whether there is a specific bad line. If it's a bad row in the history you will need to delete it manually, or maybe pipe through some command to cleanup bad unicode characters (I don't know of one OTOH but I'm sure there is one). This would be the best fix.
3. Otherwise to see if it is to do with my use of a weird separator character, revert that last change and try using something other than the weird unicode character for column separator: line 256, `local sep="#"` or something like that. This will have the side-effect of making the column spacing wrong if you have the `#` character in your history but it would provide a differential diagnostic.

**Comment by diamond-lizard** [comment]
I have "LANG=en_US.UTF-8" and "XTERM_LOCALE=en_US.UTF-8".

I tried taking out the pipe through column and that fixed the problem.

I'm in the process of bisecting and hex dumping to find the raw character codes that are upsetting column.  I'll report back once I've found something of interest.  Thanks for your help!

**Comment by diamond-lizard** [comment]
I think I found the culprit:
```
04/060~mv ../IMG_3379.JPG Ð¿ÐµÑÐµÐ´-Ð½Ð°Ñ¨Ð¸Ð¼-Ð´Ð¾Ð¼Ð¾Ð¼.jpg
```

The hexdump of it is:

```
0000000 3430 302f 1f36 1f30 1f7e 766d 2e20 2f2e
0000010 4d49 5f47 3333 3937 4a2e 4750 c320 c290
0000020 c283 c3bf c290 c3b5 c291 c380 c290 c3b5
0000030 c290 2db4 90c3 bdc2 90c3 b0c2 91c3 83c2
0000040 a8c2 90c3 b8c2 90c3 bcc2 c32d c290 c3b4
0000050 c290 c3be c290 c3bc c290 c3be c290 2ebc
0000060 706a 0a67
0000064
```
And here it is base64 encoded:

```
MDQvMDYfMB9+H212IC4uL0lNR18zMzc5LkpQRyDDkMKDwr/DkMK1w5HCgMOQwrXDkMK0LcOQwr3D
kMKww5HCg8Kow5DCuMOQwrwtw5DCtMOQwr7DkMK8w5DCvsOQwrwuanBnCg==
```

For some reason, github and gist don't seem to want to accept the little 100 byte file containing this text, so I'm unable to upload it to either of them.  Hopefully the base64 and hexdump will help you reconstruct the original or at least give some insight as to what might be going wrong.

**Comment by diamond-lizard** [comment]
I've been able to narrow down the problematic character to just that "<83>" itself.

The hexdump of it is:

```
0000000 0a83
0000002
```

The "od" output is:

```
0000000 005203
0000002
```

And base64 encoded it is:

```
gwo=
```

Simply piping that one character through column results in: `"column: read failed: Invalid or incomplete multibyte or wide character"`

**Comment by larkery** [comment]
OK - I have put `iconv` in the pipeline to delete invalid characters, so that might fix it. Let me know...

**Comment by diamond-lizard** [comment]
That fixed it!  Awesome.  Thank you so much!

**Comment by larkery** [comment]
Radical
