### ISSUE TITLE
Multiline commands should appear with \n

### ISSUE THREAD

**Issue by vitalybe** [larkery/zsh-histdb#26]
Currently it shows the actual new line character

**Comment by vitalybe** [comment]
For example, this line in `history`:

` 1170  echo Hi\necho Bye`

Appears in `histdb` as:

```
22:37     19   ~/.oh-my-zsh/custom/plugins/zsh-histdb                            echo Hi
echo Bye
```

**Comment by larkery** [comment]
This is as intended, I do not want to see the \n - it has an actual new line in it, so that's what gets printed. The output is not intended for line-based parsing, if that's what's causing the problem. It should be aligned into the appropriate column, so if that isn't working there is a small bug.

If you do want to use the database contents in some fancy way, I suggest reading the database directly and writing some queries against it.
