### ISSUE TITLE
Database locked when using tmux's `synchronize-panes`

### ISSUE THREAD

**Issue by a3ammar** [larkery/zsh-histdb#27]
Hi,
Recently I discovered tmux's `synchronize-panes` command and when I turn it on and I execute a command I get a lock error in all the other panes:

```
Error: database is locked
error in insert into commands (argv) values (...);
insert into places   (host, dir) values (..., ...);
insert into history
  (session, command_id, place_id, exit_status, start_time, duration)
select
  381,
  commands.rowid,
  places.rowid,
  0,
  1518591321,
  1518591321 - 1518591321
from
  commands, places
where
  commands.argv = ... and
  places.host = ... and
  places.dir = ...
;
```

I know this is an edge case that shouldn't be handled by this project but is there a way to turn off histdb in a session?

**Comment by larkery** [comment]
Ah right, this will happen if two shells try and write concurrently you could either modify the `_histdb_query` function to block instead of erroring out, by doing something like

```
_histdb_query () {
    sqlite3 "${HISTDB_FILE}" ".timeout 100
$@"
    [[ "$?" -ne 0 ]] && echo "error in $@"
}
```

Which will let it block for 100ms on a write lock. 

Alternatively I think you should be able to disable it for the rest of a session by undefining `zshaddhistory` with `unfunction zshaddhistory`.

**Comment by a3ammar** [comment]
Very neat, thanks!

**Comment by tmpm697** [comment]
I saw timeout's increased to 1000 in `_histdb_query`  but I still get this error when use shell script to create windows and panes (I map to a key that will trigger to create multiple windows and panes).
